name: UpDown
description: "UpDown project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.6.0

dependencies:
    cupertino_icons: ^1.0.8
    either_dart: ^1.0.0
    flutter:
        sdk: flutter
    flutter_bloc: ^9.1.1
    flutter_localizations:
        sdk: flutter
    # Responsive Design
    flutter_screenutil: ^5.9.3
    # Dependency Injection
    get_it: ^8.0.3
    # Routing
    go_router: ^14.6.2
    # Fonts
    google_fonts: ^6.2.1
    # Image Picker
    image_picker: ^1.1.2
    # Storage Services
    flutter_secure_storage: ^9.2.4
    shared_preferences: ^2.5.3
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    # Date Format
    intl: ^0.20.2
    # Svg
    flutter_svg: ^2.0.17
    # Api services
    supabase_flutter: ^2.8.2
    firebase_core: ^3.13.0
    # Compress files
    flutter_image_compress: ^2.4.0
    video_compress: ^3.1.4
    mime: ^2.0.0

    # Path Provider
    path: ^1.9.1
    path_provider: ^2.1.5
    # Encryption
    crypto: ^3.0.6
    # Skeleton
    skeletonizer: ^2.0.1
    # Network
    internet_connection_checker_plus: ^2.7.2
    retry: ^3.1.2
    cached_network_image: ^3.4.1
    # Stream controller
    rxdart: ^0.28.0
    # Annotations
    json_annotation: ^4.9.0
    freezed_annotation: ^2.4.4
    collection: ^1.19.1

dev_dependencies:
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter
    # Code generation
    flutter_gen: ^5.10.0
    hive_generator: ^2.0.1
    build_runner: ^2.4.15
    freezed: ^2.5.7
    json_serializable: ^6.9.0
    package_rename: ^1.10.0

# The following section is specific to Flutter packages.
flutter:
    uses-material-design: true
    generate: true

    assets:
        - assets/images/
        - assets/svgs/
    fonts:
        - family: NotoKufiArabic
          fonts:
              - asset: assets/fonts/NotoKufiArabic.ttf

# Localization-specific configuration
l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: lib/l10n/generated/app_localizations.dart
