// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYT2koSEPBgGqYTBvEdKPeTIb9o_sml4',
    appId: '1:669185880498:web:e3640b20922fbb6f5db4ab',
    messagingSenderId: '669185880498',
    projectId: 'updown-6eb83',
    authDomain: 'updown-6eb83.firebaseapp.com',
    storageBucket: 'updown-6eb83.firebasestorage.app',
    measurementId: 'G-NQPS3TGLVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWVQOegSWtjvLX5N6wnuuuHywsjQOIl8',
    appId: '1:669185880498:android:e297335d2f59c3a45db4ab',
    messagingSenderId: '669185880498',
    projectId: 'updown-6eb83',
    storageBucket: 'updown-6eb83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpHe6ViFllW_EkPKN_NWdk9_dQXFP1KvE',
    appId: '1:669185880498:ios:130fba394fbbc5645db4ab',
    messagingSenderId: '669185880498',
    projectId: 'updown-6eb83',
    storageBucket: 'updown-6eb83.firebasestorage.app',
    iosBundleId: 'com.updown.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpHe6ViFllW_EkPKN_NWdk9_dQXFP1KvE',
    appId: '1:669185880498:ios:130fba394fbbc5645db4ab',
    messagingSenderId: '669185880498',
    projectId: 'updown-6eb83',
    storageBucket: 'updown-6eb83.firebasestorage.app',
    iosBundleId: 'com.updown.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWYT2koSEPBgGqYTBvEdKPeTIb9o_sml4',
    appId: '1:669185880498:web:07ac4584f38cb9fd5db4ab',
    messagingSenderId: '669185880498',
    projectId: 'updown-6eb83',
    authDomain: 'updown-6eb83.firebaseapp.com',
    storageBucket: 'updown-6eb83.firebasestorage.app',
    measurementId: 'G-6EQ3Y5E7SE',
  );

}